export const STATUS = {
  NOT_STARTED: "NOT_STARTED",
  PENDING: "PENDING",
  CLONING: "CLONING",
  INDEXING: "INDEXING",
  ANALYZING: "ANALYZING",
  AI_PROCESSING: "AI_PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};