# Generated by Django 5.2.15 on 2026-07-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLONING', 'Cloning'), ('INDEXING', 'Indexing'), ('ANALYZING', 'Analyzing'), ('AI_PROCESSING', 'Generating AI Insights'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('branch', models.CharField(max_length=255)),
                ('commit_sha', models.CharField(db_index=True, max_length=40)),
                ('analysis_version', models.CharField(default='1.0.0', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='repositories.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
